# Site settings
title: 😾💻 (xtonousou)
person_name: Sotirios M. Roussis
person_nickname: xtonousou
email: "xtonousou@gmail.com"
description: "FullStack Web Developer / SysAdmin / Google-fu Expert"
key: "pubkey.gpg"
cv: "cv.pdf"
baseurl: "" # the subpath of your site, e.g. /blog/
hostname: xtonousou.github.io # used to determine if google analytics should be triggered
url: https://xtonousou.github.io # the base hostname & protocol for your site
permalink: /:title/
exclude: [vendor] # avoid irritating errors

#blog_url: url_here
#cv_url: url_here
#vcard_url: url_here
#facebook_username: xtonousou
twitter_username: xtonousou
github_username: xtonousou
stackoverflow:
  id: 4946732
  username: xtonousou
spotify_username: xtonousou
youtube_username: TheToNouSou96
deviantart_username: xtonousou

# Build settings
markdown: kramdown
